# docker-compose.yml
# This file defines the services for your application and its dependencies.
# The 'supershopcart-backend' service will build and run your Spring Boot application,
# and it will connect to the 'firebase-emulator' service for Firestore operations.

services:
  supershopcart-backend:
    # Builds the Docker image for the Spring Boot application using the Dockerfile
    # in the current directory.
    build: .
    container_name: supershopcart-backend
    ports:
      # Maps the container's port 8080 to port 8080 on your host machine.
      - "8080:8080"
    depends_on:
      # Ensures the firebase-emulator container is started before the backend.
      - firebase-emulator
    environment:
      # Activates the 'dev-emulator' profile to use the correct configuration
      # for the Firestore emulator and the H2 in-memory database.
      - SPRING_PROFILES_ACTIVE=dev-emulator
      # Points the Spring Boot application to the Firestore emulator using
      # the service name defined in this file. This works because all
      # services are on the same Docker network.
      - FIRESTORE_EMULATOR_HOST=firebase-emulator:8081
      # Note: JWT and OAuth secrets from application-dev-emulator.properties
      # can be defined here or read from the properties file.
      # Defining them here is a good practice for multi-container setups.
      - JWT_SECRET=bb7fe82af6c5edcc8bc7da50d9ab448331a29bbb12c2559782fa1f3c8fafa81d
      - JWT_ACCESS_TOKEN_EXPIRATION=3600000
      - JWT_REFRESH_TOKEN_EXPIRATION=2592000000
      - OAUTH_ID=656975893985-nnh8pl4ul2b8ve4uc0514u0h06f93hs.apps.googleusercontent.com

  firebase-emulator:
    image: node:18
    container_name: firebase-emulator
    working_dir: /app
    ports:
      # Maps the container's port 8081 to host's port 8081 for Firestore.
      - "8081:8081"
      # Maps the container's port 4001 to host's port 4001 for the Emulator UI.
      - "4001:4001"
      # Maps the container's port 9099 to host's port 9099 for Auth.
      - "9099:9099"
    volumes:
      - .:/app
      - firebase_data:/app/.firebase
    command: >
      bash -c "
        apt-get update &&
        apt-get install -y default-jre &&
        npm install -g firebase-tools &&
        firebase emulators:start --only firestore,ui,auth --project devsupershoppercart --token fake-token
      "
    environment:
      # FIRESTORE_EMULATOR_HOST is set to 0.0.0.0 so it is accessible from other containers.
      - FIRESTORE_EMULATOR_HOST=0.0.0.0:8081
      - FIREBASE_TOKEN=fake-token
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

volumes:
  firebase_data: