# docker-compose.yml
# Improved configuration with better practices
version: '3.8'

services:
  supershopcart-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: supershopcart-backend
    ports:
      - "8080:8080"
    depends_on:
      firebase-emulator:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=dev-emulator
      - FIRESTORE_EMULATOR_HOST=firebase-emulator:8081
      - JWT_SECRET=bb7fe82af6c5edcc8bc7da50d9ab448331a29bbb12c2559782fa1f3c8fafa81d
      - JWT_ACCESS_TOKEN_EXPIRATION=3600000
      - JWT_REFRESH_TOKEN_EXPIRATION=2592000000
      - OAUTH_ID=656975893985-nnh8pl4ul2b8ve4uc0514u0h06f93hs6.apps.googleusercontent.com
    networks:
      - supershopcart-network
    restart: unless-stopped

  firebase-emulator:
    image: node:18-alpine
    container_name: firebase-emulator
    working_dir: /app
    ports:
      - "8081:8081"  # Firestore
      - "4001:4001"  # Emulator UI
      - "9099:9099"  # Auth
    volumes:
      - ./firebase.json:/app/firebase.json:ro
      - ./firestore.rules:/app/firestore.rules:ro
      - firebase_data:/app/.firebase
    command: >
      sh -c "
        npm install -g firebase-tools &&
        firebase emulators:start --only firestore,ui,auth --project fir-supershopcart-dev-emulator
      "
    environment:
      - FIRESTORE_EMULATOR_HOST=0.0.0.0:8081
    networks:
      - supershopcart-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8081"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

networks:
  supershopcart-network:
    driver: bridge

volumes:
  firebase_data:
